DROP TABLE IF EXISTS PUBLIC.BOOKS;

CREATE TABLE PUBLIC.BOOKS (
  ID         INTEGER NOT NULL AUTO_INCREMENT,
  NAME       VARCHAR NOT NULL,
  AUTOR      VARCHAR NOT NULL,
  PRINT_YEAR INTEGER NOT NULL,
  IS_READ    BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`ID`)
)
