DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS (
  ID        INTEGER NOT NULL AUTO_INCREMENT,
  NAME      VARCHAR NOT NULL,
  AUTOR     VARCHAR NOT NULL,
  PRINTYEAR INTEGER NOT NULL,
  ISREAD    BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`ID`)
)
