DROP TABLE IF EXISTS PUBLIC.BOOKS;

CREATE TABLE PUBLIC.BOOKS (
  ID         INTEGER      NOT NULL AUTO_INCREMENT,
  NAME       VARCHAR(255) NOT NULL,
  AUTHOR     VARCHAR(255) NOT NULL,
  PRINT_YEAR INTEGER(4)   NOT NULL,
  IS_READ    BOOLEAN      NOT NULL DEFAULT FALSE,
  CONSTRAINT BOOKS_PRIMARY_KEY PRIMARY KEY (ID)
)
